package com.lt.dom.otcenum;

public enum EnumActivityType {
    GENERAL,
    CONTACT_CREATED,
    MEMBER_LOGIN,
    MEMBER_REGISTER,
    MEMBER_STATUS_CHANGED,
    FORM_SUBMITTED,
    INBOX_FORM_SUBMITTED,
    INBOX_PAYMENT_REQUEST_PAID,
    INBOX_MESSAGE_TO_CUSTOMER,
    INBOX_MESSAGE_FROM_CUSTOMER,
    NEWSLETTER_SUBSCRIPTION_FORM_SUBMITTED,
    NEWSLETTER_SUBSCRIPTION_UNSUBSCRIBE,
    ECOM_PURCHASE,
    ECOM_CART_ABANDON,
    ECOM_CHECKOUT_BUYER,
    BOOKINGS_APPOINTMENT,
    HOTELS_RESERVATION,
    HOTELS_PURCHASE,
    HOTELS_CONFIRMATION,
    HOTELS_CANCEL,
    VIDEO_PURCHASE,
    VIDEO_RENT,
    CASHIER_BUTTON_PURCHASE,
    ARENA_NEW_LEAD,
    EVENTS_RSVP,
    INVOICE_PAY,
    INVOICE_OVERDUE,
    PRICE_QUOTE_ACCEPT,
    PRICE_QUOTE_EXPIRE,
    RESTAURANTS_ORDER,
    RESTAURANTS_RESERVATION,
    SHOUTOUT_OPEN,
    SHOUTOUT_CLICK,
    CONTACT_MERGED;

    ;

    EnumActivityType() {

    }
}
