
spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

  security:
    user:
      name: user
      password: 123
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 123

  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

lt:
  url: http://localhost:8080

# 服务商 AppID
wxpay:
  app_id: wx06706b4df0e7e9ec
  # 商户号
  mch_id: 1326370001
  # 子商户号
  sub_mch_id: 1326370001
  # 商户的 key（私钥）
  key: PHC578EWS415THG321GTQ874YLKEE666
  # 证书地址
  cert_path: /xxx/xxxx/xx/apiclient_cert.p12
  # API 支付请求地址
  pay_url: https://api.mch.weixin.qq.com/pay/unifiedorder
  # API 查询请求地址
  query_url: https://api.mch.weixin.qq.com/pay/orderquery
  # package
  package_value: Sign=WXPay
  # 回调地址
  tenpay_order_callback: https://39.106.34.220:8080/oct/xxxxxx
  # 交易类型
  trade_type_app: APP


  refundNotifyUrl: https://bfb3-221-237-148-6.ap.ngrok.io/wechat/pay/refund_notify


wx:
  app_id: wxada5ab1a8c131d85
  secret: bdde4cd0c7eff399037992a53dba9826

jwt:
  secret: 123



dll:
  path:
    printer: \TSCLIB
    idcard: .\dll\sdtapi

logging:
  level:
    org:
      springframework:
        security: DEBUG

# App Properties


bezkoder:
  app:
    jwtExpirationMs: 86400000
    jwtSecret: bezKoderSecretKey